###############################
######## Keybinds #############
#    ctrl x ? for shortcult   #
###############################
###############################

set -g history-limit 10000

# Changing ctrl b to ctrl x as the command button
unbind C-b
set -g prefix C-x

# set first window to index 1 (not 0) to map more to the keyboard layout
set -g base-index 1
set -g pane-base-index 1

# rename window to reflect current program and when windows is closed or open
setw -g automatic-rename on   
set -g renumber-windows on 

# pass through xterm keys
set -g xterm-keys on

# Keep your finger on ctrl, or don't, same result
bind-key C-d detach-client
bind-key C-p paste-buffer

# Redraw the client (if interrupted by wall, etc)
bind R refresh-client

# reload tmux config with ctrl + x + r
unbind r
bind r \
    source-file ~/.tmux.conf \;\
        display 'Reloaded tmux config.'

# Vertical splits with o or C-o
unbind o 
unbind C-o
bind-key o split-window -h
bind-key C-o split-window -h

# Horizontal splits with p or C-p
unbind p
unbind C-p
bind-key p split-window
bind-key C-p split-window

# Using the mouse to switch panes and resize panes
set -g mouse on

# Ctrl - t or t new window
unbind t
unbind C-t
bind-key t new-window
bind-key C-t new-window

# Ctrl - w or w to kill panes
unbind w
unbind C-w
bind-key w kill-pane
bind-key C-w kill-pane

# C + control q to kill session
unbind q
unbind C-q
bind-key q kill-session
bind-key C-q kill-session

# Show tmux positions in titles
set -g set-titles on

# Vim-like pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Vim-like windows navigation
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+
bind b previous-window

# Resize the current pane using alt + vim-like navigation
bind -n M-k resize-pane -U 5
bind -n M-j resize-pane -D 5
bind -n M-h resize-pane -L 5
bind -n M-l resize-pane -R 5

# press ctrl x and space to switch layout

set -g status-keys vi
setw -g mode-keys vi
setw -g monitor-activity on

######################
######################

set -g default-terminal "tmux-256color"

# Tokyonight theme
#

# Status update interval
set -g status-interval 1

#
# Colors
#
tmux_status_bg=#232433
tmux_status_fg=colour7

#first set of side status
tmux_status_bg_1=colour8
tmux_status_fg_1=colour4

#second set of side status
tmux_status_bg_2=colour4
tmux_status_fg_2=colour0

tmux_accent=colour1
tmux_current_title_fg=colour2
tmux_activity_color=colour3

# Basic status bar colors
set -g status-style bg=$tmux_status_bg

# Left side of status bar
set -g status-left-style bg=colour233,fg=colour243
set -g status-left-length 40
set -g status-left ""

# Right side of status bar
set -g status-right-style bg=colour233,fg=colour243
set -g status-right-length 150
set -g status-right "#[fg=$tmux_accent,bg=$tmux_status_bg_1,bold] %H:%M:%S #[fg=$tmux_status_fg_2,bg=$tmux_status_bg_2,nobold] %a %d %b %y "

# Window status
set -g window-status-format "#[fg=$tmux_status_fg_1,bg=$tmux_status_bg_1] #I #[fg=default,bg=default] #W #[default]"
set -g window-status-current-format "#[fg=$tmux_accent,bg=$tmux_status_bg_1,bold] #I #[fg=$tmux_current_title_fg,bg=$tmux_status_bg,bold] #W #[default]"

# Current window status
set -g window-status-current-style none

# Window with activity status
set -g window-status-activity-style bg="$tmux_status_bg",fg="$tmux_activity_color"

# Window separator
set -g window-status-separator ""

# Window status alignment
set -g status-justify left

# Pane border
set -g pane-border-style bg=default,fg="$tmux_status_bg"

# Active pane border
set -g pane-active-border-style bg=default,fg="$tmux_status_bg_2"

# Pane number indicator
set -g display-panes-colour "$tmux_status_bg_2"
set -g display-panes-active-colour "$tmux_accent"


# Clock mode
set -g clock-mode-colour "$tmux_status_bg_2"
set -g clock-mode-style 24
